"""Prompts package."""
from prompts.planner import PLANNER_SYSTEM_PROMPT, PLANNER_USER_TEMPLATE
from prompts.analyst import COMPETITOR_ANALYST_PROMPT
from prompts.synthesizer import SYNTHESIZER_SYSTEM_PROMPT, SYNTHESIZER_USER_TEMPLATE
from prompts.verifier import CLAIM_EXTRACTION_PROMPT, FACT_CHECKER_PROMPT

__all__ = [
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_USER_TEMPLATE",
    "COMPETITOR_ANALYST_PROMPT",
    "SYNTHESIZER_SYSTEM_PROMPT",
    "SYNTHESIZER_USER_TEMPLATE",
    "CLAIM_EXTRACTION_PROMPT",
    "FACT_CHECKER_PROMPT"
]
