"""Research plan, scope, and task schemas."""
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field
import uuid

class ResearchScope(BaseModel):
    """Scope boundaries for research execution."""
    companies: List[str] = Field(default_factory=list)
    market_sector: str = Field(default="Technology")
    focus_areas: List[str] = Field(
        default_factory=lambda: [
            "Financial Performance",
            "AI Strategy & Architecture",
            "Recent Developments & M&A",
            "Competitive Advantages & Moats",
            "Risks & Regulatory Challenges"
        ]
    )
    date_range: Optional[str] = Field(default="Last 12 Months")
    research_objective: str = Field(default="Competitive landscape and strategic benchmarking")

class ResearchTask(BaseModel):
    """A decomposed discrete research assignment."""
    task_id: str = Field(default_factory=lambda: f"task-{uuid.uuid4().hex[:6]}")
    agent_type: str = Field(..., description="Target agent: web | financial | news")
    target_company: Optional[str] = Field(None, description="Company under investigation")
    query: str = Field(..., description="Optimized search query")
    objective: str = Field(..., description="What specific information this task aims to uncover")
    priority: int = Field(default=1, description="Priority level 1-3")

class ResearchPlan(BaseModel):
    """Structured plan generated by the Planning Agent."""
    user_query: str
    scope: ResearchScope
    tasks: List[ResearchTask] = Field(default_factory=list)
    strategy_summary: str = Field(default="")
